import {
  GitHubLogoIcon,
  LinkedInLogoIcon,
  TwitterLogoIcon,
} from "@radix-ui/react-icons";
import {
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Check,
  Globe,
  Link,
  Loader2,
  Mail,
  Menu,
  Moon,
  Phone,
  Send,
  SunMedium,
  SunMoon,
} from "lucide-react";

export const Icons = {
  sunMedium: SunMedium,
  moon: Moon,
  menu: Menu,
  link: Link,
  send: Send,
  phone: Phone,
  website: Globe,
  arrowUp: ArrowUp,
  github: GitHubLogoIcon,
  twitter: TwitterLogoIcon,
  linkedin: LinkedInLogoIcon,
  mail: Mail,
  check: Check,
  loader: Loader2,
  sunMoon: SunMoon,
  arrowRight: ArrowRight,
  arrowUpDown: ArrowUpDown,
};
