import {
  GitHubLogoIcon,
  LinkedInLogoIcon,
  TwitterLogoIcon,
} from '@radix-ui/react-icons';
import {
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Briefcase,
  Check,
  Download,
  Globe,
  GraduationCap,
  Languages,
  Link,
  Loader2,
  Mail,
  Menu,
  Moon,
  Phone,
  Send,
  SunMedium,
  SunMoon,
  UserPen,
} from 'lucide-react';

export const Icons = {
  sunMedium: SunMedium,
  moon: Moon,
  menu: Menu,
  link: Link,
  send: Send,
  contact: UserPen,
  briefcase: Briefcase,
  graduation: GraduationCap,
  phone: Phone,
  website: Globe,
  arrowUp: ArrowUp,
  download: Download,
  language: Languages,
  github: GitHubLogoIcon,
  twitter: TwitterLogoIcon,
  linkedin: LinkedInLogoIcon,
  mail: Mail,
  check: Check,
  loader: Loader2,
  sunMoon: SunMoon,
  arrowRight: ArrowRight,
  arrowUpDown: ArrowUpDown,
};
